### GET ALL
GET http://localhost:3000/courses

### GET ONE
GET http://localhost:3000/courses/3

### POST CREATE
POST http://localhost:3000/courses
Content-Type: application/json

{
    "name": "Course NestJS 2",
    "description": "Course NestJS",
    "tags": ["NestJs", "Node", "TypeScript"]
}

### PATCH UPDATE
PATCH  http://localhost:3000/courses/4
Content-Type: application/json

{
    "name": "Courses NestJS"
}

### DELETE REMOVE
DELETE  http://localhost:3000/courses/1