version: "3"

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: nest-course
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: nest-course-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nestcourse
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: nest-course-
    tty: true
    restart: always
    ports:
      - "8000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db